config/routes.rb
Rails.application.routes.draw do
  resources :firework_years
  resources :firework_details
  resources :fireworks
  devise_for :users
  root to: "fireworks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/firework.rb
class Firework < ApplicationRecord
  has_many :firework_years
end

app/models/firework_year.rb
class FireworkYear < ApplicationRecord
  belongs_to :firework
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable, :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/firework_years_controller.rb
class FireworkYearsController < ApplicationController
  before_action :set_firework_year, only: [:show, :edit, :update, :destroy]

  # GET /firework_years
  # GET /firework_years.json
  def index
    @firework_years = FireworkYear.all
  end

  # GET /firework_years/1
  # GET /firework_years/1.json
  def show
  end

  # GET /firework_years/new
  def new
    @firework_year = FireworkYear.new
  end

  # GET /firework_years/1/edit
  def edit
  end

  # POST /firework_years
  # POST /firework_years.json
  def create
    @firework_year = FireworkYear.new(firework_year_params)

    respond_to do |format|
      if @firework_year.save
        format.html { redirect_to @firework_year, notice: 'Firework year was successfully created.' }
        format.json { render :show, status: :created, location: @firework_year }
      else
        format.html { render :new }
        format.json { render json: @firework_year.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /firework_years/1
  # PATCH/PUT /firework_years/1.json
  def update
    respond_to do |format|
      if @firework_year.update(firework_year_params)
        format.html { redirect_to @firework_year, notice: 'Firework year was successfully updated.' }
        format.json { render :show, status: :ok, location: @firework_year }
      else
        format.html { render :edit }
        format.json { render json: @firework_year.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /firework_years/1
  # DELETE /firework_years/1.json
  def destroy
    @firework_year.destroy
    respond_to do |format|
      format.html { redirect_to firework_years_url, notice: 'Firework year was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_firework_year
      @firework_year = FireworkYear.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def firework_year_params
      params.require(:firework_year).permit(:cost, :purchased, :year, :firework_id)
    end
end

app/controllers/fireworks_controller.rb
class FireworksController < ApplicationController
  before_action :set_firework, only: [:show, :edit, :update, :destroy]

  # GET /fireworks
  # GET /fireworks.json
  def index
    @fireworks = Firework.all
  end

  # GET /fireworks/1
  # GET /fireworks/1.json
  def show
  end

  # GET /fireworks/new
  def new
    @firework = Firework.new
  end

  # GET /fireworks/1/edit
  def edit
  end

  # POST /fireworks
  # POST /fireworks.json
  def create
    @firework = Firework.new(firework_params)

    respond_to do |format|
      if @firework.save
        format.html { redirect_to @firework, notice: 'Firework was successfully created.' }
        format.json { render :show, status: :created, location: @firework }
      else
        format.html { render :new }
        format.json { render json: @firework.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fireworks/1
  # PATCH/PUT /fireworks/1.json
  def update
    respond_to do |format|
      if @firework.update(firework_params)
        format.html { redirect_to @firework, notice: 'Firework was successfully updated.' }
        format.json { render :show, status: :ok, location: @firework }
      else
        format.html { render :edit }
        format.json { render json: @firework.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fireworks/1
  # DELETE /fireworks/1.json
  def destroy
    @firework.destroy
    respond_to do |format|
      format.html { redirect_to fireworks_url, notice: 'Firework was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_firework
      @firework = Firework.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def firework_params
      params.require(:firework).permit(:firework_name, :style, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/firework_years_helper.rb
module FireworkYearsHelper
end

app/helpers/fireworks_helper.rb
module FireworksHelper
end

app/views/firework_years/_form.html.erb
<%= form_with(model: firework_year, local: true) do |form| %>
  <% if firework_year.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(firework_year.errors.count, "error") %> prohibited this firework_year from being saved:</h2>

      <ul>
        <% firework_year.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cost %>
    <%= form.text_field :cost %>
  </div>

  <div class="field">
    <%= form.label :purchased %>
    <%= form.number_field :purchased %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div class="field">
    <%= form.label :firework_id %>
    <%= form.text_field :firework_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/firework_years/edit.html.erb
<h1>Editing Firework Year</h1>

<%= render 'form', firework_year: @firework_year %>

<%= link_to 'Show', @firework_year %> |
<%= link_to 'Back', firework_years_path %>

app/views/firework_years/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Firework Years</h1>

<table>
  <thead>
    <tr>
      <th>Cost</th>
      <th>Purchased</th>
      <th>Year</th>
      <th>Firework</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @firework_years.each do |firework_year| %>
      <tr>
        <td><%= firework_year.cost %></td>
        <td><%= firework_year.purchased %></td>
        <td><%= firework_year.year %></td>
        <td><%= firework_year.firework_id %></td>
        <td><%= link_to 'Show', firework_year %></td>
        <td><%= link_to 'Edit', edit_firework_year_path(firework_year) %></td>
        <td><%= link_to 'Destroy', firework_year, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Firework Year', new_firework_year_path %>

app/views/firework_years/new.html.erb
<h1>New Firework Year</h1>

<%= render 'form', firework_year: @firework_year %>

<%= link_to 'Back', firework_years_path %>

app/views/firework_years/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cost:</strong>
  <%= @firework_year.cost %>
</p>

<p>
  <strong>Purchased:</strong>
  <%= @firework_year.purchased %>
</p>

<p>
  <strong>Year:</strong>
  <%= @firework_year.year %>
</p>

<p>
  <strong>Firework:</strong>
  <%= @firework_year.firework_id %>
</p>

<%= link_to 'Edit', edit_firework_year_path(@firework_year) %> |
<%= link_to 'Back', firework_years_path %>

app/views/fireworks/_form.html.erb
<%= form_with(model: firework, local: true) do |form| %>
  <% if firework.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(firework.errors.count, "error") %> prohibited this firework from being saved:</h2>

      <ul>
        <% firework.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :firework_name %>
    <%= form.text_field :firework_name %>
  </div>

  <div class="field">
    <%= form.label :style %>
    <%= form.text_field :style %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fireworks/edit.html.erb
<h1>Editing Firework</h1>

<%= render 'form', firework: @firework %>

<%= link_to 'Show', @firework %> |
<%= link_to 'Back', fireworks_path %>

app/views/fireworks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fireworks</h1>

<table>
  <thead>
    <tr>
      <th>Firework name</th>
      <th>Style</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fireworks.each do |firework| %>
      <tr>
        <td><%= firework.firework_name %></td>
        <td><%= firework.style %></td>
        <td><%= firework.description %></td>
        <td><%= link_to 'Show', firework %></td>
        <td><%= link_to 'Edit', edit_firework_path(firework) %></td>
        <td><%= link_to 'Destroy', firework, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Firework', new_firework_path %>

app/views/fireworks/new.html.erb
<h1>New Firework</h1>

<%= render 'form', firework: @firework %>

<%= link_to 'Back', fireworks_path %>

app/views/fireworks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firework name:</strong>
  <%= @firework.firework_name %>
</p>

<p>
  <strong>Style:</strong>
  <%= @firework.style %>
</p>

<p>
  <strong>Description:</strong>
  <%= @firework.description %>
</p>

<%= link_to 'Edit', edit_firework_path(@firework) %> |
<%= link_to 'Back', fireworks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Fireworks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a <%= link_to "Firework List", root_path, class: 'navbar-brand' %>>Fireworks</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <button type="button" class="btn btn-secondary" data-toggle="tooltip" data-placement="top" title="Tooltip on top">
      Tooltip on top
    </button>
    <button type="button" class="btn btn-secondary" data-toggle="tooltip" data-placement="right" title="Tooltip on right">
      Tooltip on right
    </button>
    <button type="button" class="btn btn-secondary" data-toggle="tooltip" data-placement="bottom" title="Tooltip on bottom">
      Tooltip on bottom
    </button>
    <button type="button" class="btn btn-secondary" data-toggle="tooltip" data-placement="left" title="Tooltip on left">
      Tooltip on left
    </button>

    <button type="button" class="btn btn-lg btn-danger" data-toggle="popover" title="Popover title" data-content="And here's some amazing content. It's very engaging. Right?">Click to toggle popover</button>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>